Implement structured logging
bitnami-labs/sealed-secrets pull request #1438
Opened 2024-01-18 20:27 UTC by mohamed-essam

**Description of the change**

Change controller logging to use `log/slog`.

**Benefits**

1. Allow structured logging.
2. Allow changing logging format between text and JSON.
3. Allow changing logging level.

**Possible drawbacks**

N/A

**Applicable issues**

- fixes #1285 

**Additional information**

* I took the liberty of removing log at line 91 in pkg/controller/main.go as it only served as a separator
* To implement the functionality of `--log-info-to-stdout`, I had to implement a custom handler that would hand logs down to one of two slog.Loggers in place of the package in `pkg/log` that handled this previously

2024-01-22 15:15 UTC, tewfik-ghariani commented on helm/sealed-secrets/templates/deployment.yaml
> +            - --log-level
log-format* ^^

2024-01-22 15:19 UTC, mohamed-essam commented on helm/sealed-secrets/templates/deployment.yaml
> +            - --log-level
Thanks for spotting this :pray:

2024-01-25 15:03 UTC, alemorcuq requested changes
Thanks @mohamed-essam! Please, check my comments. The PR looks awesome.

2024-01-25 15:16 UTC, mohamed-essam commented on pkg/controller/main.go
> +	// Set logging
Thanks @alemorcuq for your observations :pray:

2024-01-25 15:17 UTC, mohamed-essam commented on pkg/controller/main.go
> +	(&logLevel).UnmarshalText([]byte(f.LogLevel))
For some reason it was behaving weirdly with my IDE for a while but apparently I had an issue with gopls

2024-01-25 15:31 UTC, alemorcuq commented on cmd/controller/main.go
> +	slog.Info("controller version", "version", VERSION)
I agree, we can move it to the if condition. The version is already being printed in the logs when starting the container 👍

2024-01-25 15:50 UTC, alemorcuq commented on pkg/controller/server.go
> +			slog.Error("Error handling /v1/verify request: %v", err)
Could you please check all the `slog.Error` calls in this file? There are still some of them without the `error` field.

2024-01-25 16:55 UTC, mohamed-essam commented on pkg/controller/server.go
> +			slog.Error("Error handling /v1/verify request: %v", err)
Sorry misunderstood your comment as a missed line not lines, fixed.

2024-01-26 09:27 UTC, merged