add namespace to error metrics
bitnami-labs/sealed-secrets pull request #471
Opened 2020-11-01 14:40 UTC by povilasv

- add namespace to unseal error metric
- Add HTTP request and duration metrics

2020-11-14 06:31 UTC, povilasv commented
@mkmik hope you are doing well!

Any chance you have time to take a look? Would love to get some feedback from you!

2020-11-20 04:09 UTC, kskewes commented
Cool. Looking on phone and haven't looked at the Prometheus docs for the handler wrapper function.

Do you use Grafana? 
If so would you like to add a couple of panels to the dashboard? 
Perhaps using rate of requests for counter and then p50, p90, p99 quantiles for duration?

2020-11-20 10:07 UTC, mkmik commented
@povilasv  could you please rebase? I switched to GH actions so that also PRs can run integration tests

2020-11-20 10:10 UTC, mkmik commented on cmd/controller/metrics.go
> +			Name:      "request_duration_seconds",
```suggestion
			Name:      "http_request_duration_seconds",
```

2020-11-20 10:10 UTC, mkmik commented on cmd/controller/metrics.go
> +			Name:      "api_requests_total",
https://prometheus.io/docs/practices/naming/

```suggestion
			Name:      "http_requests_total",
```

2020-11-21 09:41 UTC, povilasv commented
Rebased and fixed the comments :) 

@kskewes I do, but I haven't worked on it yet

2020-11-21 16:47 UTC, kskewes requested changes

2020-11-21 16:47 UTC, kskewes commented on cmd/controller/metrics.go
> +	counter = prometheus.NewCounterVec(
```suggestion
	httpRequestsTotal = prometheus.NewCounterVec(
```

2020-11-21 16:47 UTC, kskewes commented on cmd/controller/metrics.go
> +	duration = prometheus.NewHistogramVec(
```suggestion
	httpRequestDurationSeconds = prometheus.NewHistogramVec(
```

2020-11-21 16:47 UTC, kskewes commented on cmd/controller/metrics.go
> +	prometheus.MustRegister(counter)
```suggestion
	prometheus.MustRegister(httpRequestsTotal)
```

2020-11-21 16:47 UTC, kskewes commented on cmd/controller/metrics.go
> +	prometheus.MustRegister(duration)
```suggestion
	prometheus.MustRegister(httpRequestDurationSeconds)
```

2020-11-21 16:47 UTC, kskewes commented on cmd/controller/metrics.go
> +	counter = prometheus.NewCounterVec(
We're likely to have more counters and histograms later.

2020-11-24 08:02 UTC, povilasv commented
@kskewes thanks for taking a look :1st_place_medal: . Applied you suggestions ;)

2020-11-24 09:08 UTC, mkmik approved these changes

2020-11-24 09:08 UTC, merged