helm: add ability to add custom environment variable
bitnami-labs/sealed-secrets pull request #610
Opened 2021-07-17 09:36 UTC by zufardhiyaulhaq

Add ability to add custom environment variables to the container deployment.

2021-10-30 15:56 UTC, zufardhiyaulhaq commented
cc @anguslees

2022-02-03 10:49 UTC, juan131 requested changes
Thanks so much for this PR @zufardhiyaulhaq !! Please check my recommendations when you have a chance.

2022-02-03 10:49 UTC, juan131 commented on helm/sealed-secrets/templates/deployment.yaml
> +          {{- end }}
This is my suggestion for supporting custom env vars from different sources:
```suggestion
         {{- if .Values.extraEnvVars }}
         env: {{- include "sealed-secrets.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if or .Values.extraEnvVarsCM .Values.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
            {{- end }}
          {{- end }}
```

2022-02-03 10:49 UTC, juan131 commented on helm/sealed-secrets/values.yaml
> +#   value: 1
Following the previous recommendation:
```suggestion
## @param extraEnvVars Array with extra environment variables to add to controller container
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []
## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars for controller container
##
extraEnvVarsCM: ""
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for controller container
##
extraEnvVarsSecret: ""
```

2022-02-06 12:44 UTC, zufardhiyaulhaq commented
@juan131 I am not sure why we only allow a single configmap and secret to be able to mount to the deployment. I think it's not a generic approach

2022-02-07 08:01 UTC, juan131 commented
What do you mean @zufardhiyaulhaq ? Are you suggesting that `extraEnvVarsCM` and `extraEnvVarsSecret` properties should be an array?

2022-04-25 18:39 UTC, zufardhiyaulhaq commented
yes @juan131 wdyt? it's better for array right?

2022-05-18 01:30 UTC, closed without merging