Fixes #620 by using tpl function for most probable templated values
bitnami-labs/sealed-secrets pull request #621
Opened 2021-08-13 08:11 UTC by gcaracuel

2021-09-10 11:13 UTC, gcaracuel commented
Is there somebody working on this project?

2021-12-23 08:24 UTC, juan131 requested changes
Hi @gcaracuel 

Thanks for your PR! Please note your changes are assuming a values structure that isn't valid anymore in the `2.x.x` version of the chart.

2021-12-23 08:24 UTC, juan131 commented on helm/sealed-secrets/templates/ingress.yaml
> +  {{- end }}
The `.Values.ingress.tls` isn't a map anymore but a boolean, see:
- https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml#L164
You can use `.Values.ingress.extraTls` to add TLS configuration additional hostname(s), see:
- https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml#L192

2021-12-23 08:24 UTC, juan131 commented on helm/sealed-secrets/templates/ingress.yaml
> +    - host: {{ tpl . $ }}
The `.Values.ingress.hosts` parameter is deprecated, use `.Values.ingress.extraHosts` instead to add additional hostname(s):
- https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml#L174

2022-01-27 07:30 UTC, juan131 commented
I'll proceed this PR since it seems it has no activity, please feel free to reopen it.

2022-01-27 07:30 UTC, closed without merging