Use Istio port name naming convention
bitnami-labs/sealed-secrets pull request #648
Opened 2021-10-06 15:21 UTC by sathieu

See https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection

Signed-off-by: Mathieu Parent <math.parent@gmail.com>

2021-12-15 09:04 UTC, sathieu commented
@juan131 Please review :pray:.

2021-12-16 12:54 UTC, juan131 commented
hanks so much for your contribution @sathieu!!

We're performing a major refactorization of the chart at https://github.com/bitnami-labs/sealed-secrets/pull/687
Let's wait until this is done before continue with your changes

2021-12-16 15:14 UTC, juan131 commented
@sathieu the new major version was just released! 
```
$ helm repo update sealed-secrets
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "sealed-secrets" chart repository
Update Complete. ⎈Happy Helming!⎈
$  helm search repo sealed-secrets/sealed-secrets
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION
sealed-secrets/sealed-secrets	2.0.0        	v0.17.1    	Helm chart for the sealed-secrets controller.
```
Please feel to rebase this branch in your fork with the latest changes in the main branch, and update this PR.

2021-12-23 08:18 UTC, juan131 requested changes
Thanks so much for the PR @sathieu !! Please check my comments

2021-12-23 08:18 UTC, juan131 commented on cmd/kubeseal/main.go
> +	controllerPortName = flag.String("controller-port-name", "", "Port name of sealed-secrets controller.")
It seems this parameter isn't used in the `main()` function when invoking the `run` function... Also.. It seems we're already assuming that the SealedSecret service has a port with name "http" in functions such as `validateSealedSecret` or `reEncryptSealedSecret`, see:

- https://github.com/bitnami-labs/sealed-secrets/blob/main/cmd/kubeseal/main.go#L316
- https://github.com/bitnami-labs/sealed-secrets/blob/main/cmd/kubeseal/main.go#L350

Couldn't do a similar assumption in `openCertCluster`?

2021-12-23 12:54 UTC, juan131 requested changes

2021-12-23 12:54 UTC, juan131 commented on helm/sealed-secrets/templates/deployment.yaml
> +            - --controller-port-name=http
Please bump the patch version in the [Chart.yaml](https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/Chart.yaml)

2021-12-23 13:03 UTC, juan131 commented on helm/sealed-secrets/templates/deployment.yaml
> +            - --controller-port-name=http
Follow up question: you're implementing this flag for `kubeseal` but the `controller` ignores it. Am I right?

2022-01-04 09:45 UTC, sathieu commented
@juan131 Comments addressed. Please review again.

2022-01-06 10:42 UTC, andoshin11 commented
This is indeed critical one. Appreciate the fix.

2022-01-11 16:29 UTC, sathieu commented
@juan131 Anything missing in this PR?

2022-01-13 07:55 UTC, juan131 approved these changes
LGTM! I can confirm this fix works

2022-01-13 08:03 UTC, sathieu commented
@juan131 Maybe this fix deserve a major version bump?

Also the CI is failing, is this related to this change?

2022-01-13 08:05 UTC, juan131 requested changes
@sathieu I just realized that this fixes the chart.. but it breaks the compatibility with the `controller.yaml` manifests that we publish at:

- https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.17.1

These manifests don't have a "http" name in the service port.

> maybe this fix deserve a major version bump?

Why do you think so? I don't see that they break backwards compatibility.

2022-01-13 11:24 UTC, juan131 commented
@sathieu I updated your branch with a suggestion that dynamically obtains the svc port name. Please let me know what you think

2022-01-13 11:30 UTC, alvneiayu approved these changes
Awesome work, LGTM

2022-01-13 12:47 UTC, sathieu commented
@juan131 Thanks.  This is great! lgtm!

2022-01-13 12:53 UTC, merged

2022-01-19 15:46 UTC, linkvt commented
Hello @juan131 , I'm addressing this here because I think your change broke the sealed-secrets-controller for k8s users with no permissions in kube-system - no blame intended.

As you can see in this line the proxier role only grants permissions to get `services/proxy` and not `services` https://github.com/bitnami-labs/sealed-secrets/blob/1490884d3b0d64c27900e63abfc0b268d49eaab2/helm/sealed-secrets/templates/role.yaml#L43-L45

I guess this is because `Services(namespace).ProxyGet` was replaced with `Services(namespace).Get`. Was there a reason for this? Otherwise I could create a PR to add `- services` to the Roles resources field to make it work again.

Thanks for checking.

2022-01-20 07:23 UTC, juan131 commented
Hi @linkvt 

You're totally right!! That should be pretty straight forward to fix since it just requires to update the RBAC permissions. I'll send a PR to fix it.

> Was there a reason for this?

We still use a proxy to access the service (I didn't change that), but previously we access the services to obtain the service port name information.

2022-01-21 13:50 UTC, chrisob commented
@juan131 Coming off of @linkvt 's comment, is there no alternative that would support using the original `Services(namespace).ProxyGet`? Reason being, just simply allowing `get services` in RBAC as is the case in #715 punches a bigger hole in RBAC which may not be desired in multitenant environments (especially considering *any* authenticated user can get the entire service's manifest!).

Maybe I'm a little over cautious, but I feel that only allowing `services/proxy` RBAC was a nice solution which prevented random users from discovering more information about sealed-secrets-controller than they need, a-la the principle of least privilege.

2022-01-21 14:15 UTC, chrisob commented
Just brainstorming here, but one approach could be to control this "discover service endpoint" functionality via feature flag, but by default have kubeseal assume the default `http` port & not attempt any service lookup.

2022-01-24 20:34 UTC, juan131 commented
Hi @chrisob 

Thanks for sharing your concerns, we really appreciate your opinion.  IMHO, the security risk is not that high. 

It limits the scope to the namespace where the SealedSecrets controller is installed, offering the opportunity to use a dedicated namespace for the controller so authenticated users can exclusively obtain the controller service metadata. Furthermore, this service is by default a "ClusterIP" service that exposes a single HTTP port, I don't think we add much value in terms of security by hiding this info from authenticated users.

2022-01-24 21:23 UTC, mkmik commented
My plan for fixing this was to create a ConfigMap with the public key 
and avoid all this mess with actively trying to talking to the controller.