add key-renew-period parameter to helm chart
bitnami-labs/sealed-secrets pull request #719
Opened 2022-01-20 18:57 UTC by ismailyenigul

**Description of the change**

**Benefits**
add key-renew-period parameter to helm chart

2022-01-24 20:46 UTC, juan131 requested changes
Thanks for this great PR! Please check my comments

2022-01-24 20:46 UTC, juan131 commented on helm/sealed-secrets/values.yaml
> +keyrenewperiod: "720h30m"
By default, the parameter shouldn't be set so the flag isn't passed, relying on the controller binary default value:
```suggestion
## @param keyrenewperiod Specifies key renewal period. Default 30 days
## e.g
## keyrenewperiod: "720h30m"
##
keyrenewperiod: ""
```

2022-01-25 07:18 UTC, alvneiayu requested changes
Could you please execute the [readme-generator](https://github.com/bitnami-labs/readme-generator-for-helm) tool to automatically regenerate the parameters tables in README.md?  Let me know if you have any problem and I will help you. Thanks in advance and really good work.

2022-01-25 10:40 UTC, juan131 approved these changes
Awesome! LGTM

2022-01-27 07:56 UTC, alvneiayu approved these changes
LGTM, thanks a lot

2022-01-27 07:57 UTC, merged