Allow setting of the clusterrolename for multiple instances of sealed…
bitnami-labs/sealed-secrets pull request #749
Opened 2022-02-17 17:47 UTC by derjohn

I use two instances in two different namespaces and RBAC creation fails for the instance in the second namespace.
Overriding the RBAC cluster role name solves the issue.

2022-02-24 08:22 UTC, juan131 requested changes
Thanks for bringing this up @derjohn 

IMHO it doesn't make sense to have N "ClusterRoles" that define the exact same rules. IMHO, we should make it possible to create N "ClusterRoleBindings" that associate the same "ClusterRole" with a different ServiceAccount.

What do you think?

2022-02-28 13:10 UTC, derjohn commented
Well,
I completely agree with you. No duplications, if they can be avoided. (DRY).

But how would you deal with two namespaces and two different rbac.serviceAccount.name=namepace-sa-one / rbac.serviceAccount.name=namepace-sa-two ?

2022-03-03 08:29 UTC, juan131 commented
As I said, we can have N "ClusterRoleBindings" that associate the same "ClusterRole" with a N different ServiceAccounts. Doesn't it make sense?

2022-05-27 12:51 UTC, rescDev commented
Hey @juan131 ,

we basically have the same issue as we're migrating to FluxV2. We need to install the controller and all resources a second time on the same cluster and face the error of having this ClusterRole twice which doesn't work. If we follow your approach, the chart would need to be able to skip the ClusterRole creation (or support custom names and allowing it to be created N times as proposed in this PR) if I understood this correctly.

So, how do we proceed with this PR ? We would really appreciate this feature

2022-08-04 09:12 UTC, josvazg commented on helm/sealed-secrets/values.yaml
> +  ## @param rbac.clusterRoleName Name of the clusterrole. To run multiple instances of sealed secrets with create RBAC true you need to set differnet rolenames.
```suggestion
  ## @param rbac.clusterRoleName Name of the cluster role. To run multiple instances of sealed secrets with create RBAC true you need to set different role names.
```

2022-08-04 10:48 UTC, alemorcuq commented
> Hey @juan131 ,
> 
> we basically have the same issue as we're migrating to FluxV2. We need to install the controller and all resources a second time on the same cluster and face the error of having this ClusterRole twice which doesn't work. If we follow your approach, the chart would need to be able to skip the ClusterRole creation (or support custom names and allowing it to be created N times as proposed in this PR) if I understood this correctly.
> 
> So, how do we proceed with this PR ? We would really appreciate this feature

Hi, @relusc.

I agree that would be a great option -- allowing the Cluster Role creation to be skipped. I don't think it makes sense to create N different Cluster Roles. We will create a follow-up PR to support this.

2022-08-04 16:06 UTC, alemorcuq commented
We have merged #906 adding the `rbac.clusterRole` parameter to control (in combination with the `rbac.create` parameter) the creation of the ClusterRole. This should be enough to deploy several charts but have only one of them create the ClusterRole.

As such, I'm closing this PR. Thanks to everyone to participated on this!

2022-08-04 16:06 UTC, closed without merging