Remove race condition in merge
bitnami-labs/sealed-secrets pull request #789
Opened 2022-03-29 14:15 UTC by mkmik

@luhko in  #788 noticed that a security analysis tool signaled a bad practice in our use of the `0660` mask in `ioutil.WriteFile` in `sealMergingInto`.

`sealMergingInto` should just update existing files, and thus technically that parameter is ignored because the permissions of the existing file are re-used. However, due to a bug in the windows version of the Go stdlib back in the day we passed `0660` as a workaround (which assumed that the user had a proper `umask`).

Now, the issue has been fixed (https://go-review.googlesource.com/c/go/+/234686/4/src/syscall/syscall_windows.go), so technically we can just do `return ioutil.WriteFile(filename, out.Bytes(), 0)`.

However, at the cost of just a few more lines of code, we can sidestep the whole problem and just open the file once, read from it and write the updated content.

This also handled well the (rare) case in which the file gets renamed while kubeseal is executing, which could cause kubeseal to write a new file with bad (0) permissions.

2022-03-31 08:46 UTC, alvneiayu approved these changes
LGTM

2022-03-31 10:00 UTC, alemorcuq reviewed
Shouldn't the file be closed after we are done with it?

2022-04-07 09:50 UTC, alvneiayu requested changes

2022-04-07 09:50 UTC, alvneiayu commented on cmd/kubeseal/main.go
> +	return nil
As @alemorcuq, we are missing to close it no?

2022-05-05 08:03 UTC, alvneiayu approved these changes
LGTM

2022-05-05 08:04 UTC, alemorcuq approved these changes

2022-05-05 08:04 UTC, merged