Cosign signature setup for release and docker image in CI
bitnami-labs/sealed-secrets pull request #810
Opened 2022-03-31 22:45 UTC by JeNeComprendPas

**Be careful**, this PR have requirements to follow before merge it.

*The objective of this PR is to add a signature process for release and docker images to the sealed secret project, trough the CI.*
The signature process use [Cosign](https://github.com/sigstore/cosign) and the [Cosign installer action](https://github.com/sigstore/cosign-installer).

**Prerequisites**
You need to have cosign installed on your computer and generate a key pair.
According to cosign documentation, if you have Go 1.17+, you can setup a development environment:
```sh
$ git clone https://github.com/sigstore/cosign
$ cd cosign
$ go install ./cmd/cosign
$ $(go env GOPATH)/bin/cosign
```

Then
```sh
$ cosign generate-key-pair
```

You have to put content of cosign.key in a github secret action named **COSIGN_KEY** and the password in a github secret action named **COSIGN_PASSWORD**

Once this is setup you have to put the public key in the repository, usually the path is **.github/workflows/cosign.pub**

**Description of the change**
Add signature to release, checksum and docker image (stored with metadata in the docker image on the registry).
This signature can be verified with

```sh
# For releases and checksum file
$ cosign verify-blob --key=url/to/public_key --signature <file>.sig <file>

# For docker image
$ cosign verify --key url/to/public_key <docker_image>
```

**Benefits**
Permit to users to verify provenance and integrity of files.

**Possible drawbacks**
If the private key is compromise, then it must be change and the public key also.

**Applicable issues**
The CI fail if the secrets are not correctly filled in.

**Additional information**
I don't write anything on the readme because I don't know where we can explain how to verify the signature of these contents. I am interested in proposals on this subject.

It might be a good idea to also consider signing the chart (you can do that directly with helm but you need a something like [keybase.io](https://keybase.io/)).

For the github Action, I've opened [this issue](https://github.com/sigstore/cosign-installer/issues/67) to ask sigstore to verify their action in the github marketstore.

2022-04-07 11:11 UTC, alemorcuq requested changes
Thanks for the PR! We are adding the public key in #814. Could you check my comments?

2022-04-07 11:11 UTC, alemorcuq commented on .github/workflows/release.yaml
> +
Remove extra line

2022-04-07 11:11 UTC, alemorcuq commented on .github/workflows/release.yaml
> +          echo -n "$COSIGN_PASSWORD" | cosign sign --key /tmp/cosign.key $TAG_CURRENT
This should be enough:

```
cosign sign --key /tmp/cosign.key $TAG_LATEST $TAG_CURRENT
```

2022-04-16 15:07 UTC, JeNeComprendPas commented
Hi,
Thanks for your feedback. Indeed it works.

2022-04-28 06:50 UTC, alvneiayu approved these changes
LGTM

2022-04-28 07:42 UTC, agarcia-oss requested changes
Let's use the latest version of the GH action.

2022-04-28 07:42 UTC, agarcia-oss commented on .github/workflows/release.yaml
> +        uses: sigstore/cosign-installer@v2.1.0
```suggestion
        uses: sigstore/cosign-installer@v2.3.0
```
Latest version of the GH action

2022-05-05 08:13 UTC, alvneiayu approved these changes
LGTM

2022-05-05 08:14 UTC, alemorcuq approved these changes

2022-05-05 08:25 UTC, agarcia-oss approved these changes
LGTM!

2022-05-05 08:26 UTC, merged