#802 Secure controller by avoiding priv esc
bitnami-labs/sealed-secrets pull request #819
Opened 2022-04-09 19:36 UTC by IoannisMatzaris

**Description of the change**
- Change the uid in the docker image
- Change the defaults for runAsUser & runAsGroup to 10001
- Change the allowPrivilegeEscalation to false
- Update the helm chart

**Benefits**
- https://avd.aquasec.com/misconfig/kubernetes/ksv001/
- https://avd.aquasec.com/misconfig/kubernetes/ksv020/
- https://avd.aquasec.com/misconfig/kubernetes/ksv021/

**Possible drawbacks**

**Applicable issues**

- fixes #802

**Additional information**

2022-05-05 08:29 UTC, alvneiayu commented
thanks @IoannisMatzaris 

We are investigating your change. I will come back asap.

Álvaro

2022-06-09 11:05 UTC, alvneiayu requested changes
hi @IoannisMatzaris 

First of all, thanks a lot for your time and your PR. The PR has some conflicts and I included a question and a comment.

Thanks a lot again

Álvaro

2022-06-09 11:05 UTC, alvneiayu commented on controller-norbac.jsonnet
> +                runAsUser: 10001,
question: this 10001 user still belongs to root group?

2022-07-03 01:31 UTC, closed without merging

2023-08-11 18:44 UTC, R011y commented
Did this change get merged after all? Currently trying to determine if users can safely set allowPrivilegeEscalation: false for sealed-secrets controller manifests.

2023-08-11 19:06 UTC, R011y commented
Any update here @agarcia-oss ?? Would be good to know if the controller.yaml can support this now.

2023-08-16 08:39 UTC, alvneiayu commented
hi @R011y 

We requested some information and changes to the user and we didn't receive answer from them. This is not already included.
We are open to continue working on this, do you want to help us contributing in this PR?

Thanks a lot

Álvaro

2023-08-17 08:22 UTC, alvneiayu commented
If you are using the generated yaml that we are releasing, we have included: https://github.com/bitnami-labs/sealed-secrets/pull/1261. Maybe it solves your problems