instruction about kubeseal installation on Linux distribution like ubuntu
bitnami-labs/sealed-secrets pull request #913
Opened 2022-08-12 11:40 UTC by NiniiGit

**Description of the change**

have amended README.md to have small instruction set about how kubeseal client can be installed on linux distro

**Benefits**

Being a newbie(and anyone like me who is heavily dependent on README.md for installation) to Kubeseal, I was initially struggling with kubeseal client installation on the Linux machine.Took a bit of time to go through the doc and couldn't find one. So I believe this will help for newcomers with installation of client easily

**Possible drawbacks**

None

**Applicable issues**

- fixes #

**Additional information**

2022-08-16 08:14 UTC, alvneiayu requested changes
hi @NiniiGit 

First of all, thanks a lot for your PR to improve our README. I included some comments.

Thanks again

Álvaro

2022-08-16 12:47 UTC, NiniiGit commented on README.md
> +wget https://github.com/bitnami-labs/sealed-secrets/releases/download/<release-tag>/kubeseal-linux-amd64 -O kubeseal
Thank you Alvaro, let me improve the same and then update here

2022-08-16 12:52 UTC, NiniiGit commented on README.md
> +wget https://github.com/bitnami-labs/sealed-secrets/releases/download/<release-tag>/kubeseal-linux-amd64 -O kubeseal
Hello @alvneiayu ,

Have updated the README.md accordingly based on your suggestion. Please could you take a look now.

Regards,
Ninad

2022-08-16 12:54 UTC, NiniiGit commented
Please could you re-review as suggestion has been implemented now

2022-08-18 07:09 UTC, alemorcuq requested changes
Thanks! Just two quick changes:

2022-08-18 07:09 UTC, alemorcuq commented on README.md
> +The `kubeseal` client can be installed on Linux, using below commands:
```suggestion
The `kubeseal` client can be installed on Linux, using the below commands:
```

2022-08-18 07:09 UTC, alemorcuq commented on README.md
> +where `release-tag` is [version tag](https://github.com/bitnami-labs/sealed-secrets/tags) of the kubeseal release you want to use. For example `v0.18.0`
```suggestion

where `release-tag` is the [version tag](https://github.com/bitnami-labs/sealed-secrets/tags) of the kubeseal release you want to use. For example: `v0.18.0`.
```

2022-08-18 07:43 UTC, NiniiGit commented
Hello @alemorcuq , have inculcated those two changes now that you suggested. Please let me know looks good to merge now from your end

2022-08-18 07:48 UTC, alemorcuq approved these changes
LGTM!

2022-08-18 07:54 UTC, alvneiayu approved these changes
LGTM

2022-08-18 07:57 UTC, merged