Allow additional volumes deployment
bitnami-labs/sealed-secrets pull request #945
Opened 2022-09-05 11:37 UTC by suetema

**Description of the change**

This PR makes within the helm chart the following changes:
 - Allow for extra volumes to be added to the Sealed Secrets controller Deployment.
 - Allow for extra volumeMounts to be added to the Sealed Secrets controller container.
 - Possibility to add annotations only to the service account.

**Benefits**

This would allow Sealed secrets to pick up certificates/secrets installed by the secret store csi driver(https://secrets-store-csi-driver.sigs.k8s.io)

I ran into the issue when combining sealed secrets with ASCP(https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html). I would bootstrap the EKS cluster with an instance of sealed secrets and to get a previously defined certificate as a secret in the cluster, I use the secret store csi driver with the AWS provider. CSI driver has option to reflect a secret volume as a k8s secret object, only after the volume has been mounted by a pod.

Without this change we would have to deploy an additional pod to the same namespace mounting the secret volume. so that then the controller can pick the secret up.

2022-09-08 15:03 UTC, alvneiayu commented
hi @suetema 

Could you include the new variables inside the helm chart README, please?

Thanks a lot

Álvaro

2022-09-09 16:13 UTC, josvazg requested changes
Marking as request changes waiting on the readme bits

2022-09-12 07:05 UTC, suetema reviewed
Entries for the new parameters have been added to the helm README

2022-09-12 07:09 UTC, alvneiayu approved these changes
LGTM

2022-09-12 07:25 UTC, josvazg approved these changes
LGTM

Thanks for this new feature!

2022-09-12 07:27 UTC, merged

2022-09-12 08:03 UTC, suetema commented
I now see that the chartversion had already increased to 2.6.2 prior to my pr.
How should I handle this in the future? Should I be the one bumping the chartversion or is this done by the maintainers?

2022-09-12 08:11 UTC, alvneiayu commented
No problem, it was my fault. I expected conflicts with our branch. I am going to fix it.

2022-09-12 08:12 UTC, suetema commented
Super, thank you!