feat: Support hostNetwork and dnsPolicy
bitnami-labs/sealed-secrets pull request #946
Opened 2022-09-06 14:33 UTC by porstswigger-tim

**Description of the change**

This change adds the `hostNetwork` and `dnsPolicy` pod attributes. This is needed in the case where you're running an EKS cluster with Cilium as a CNI you aren't able to `kubeseal` without:

```yaml
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```

**Benefits**

Enables `kubeseal` to work seamlessly using the Kubernetes API.

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

2022-09-08 14:50 UTC, josvazg commented
Thanks for this new feature @porstswigger-tim

Please, could you add the new feature documentation in the chart README?

Here:
https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/README.md#parameters

2022-09-09 16:11 UTC, josvazg requested changes
Marking as request changes waiting on the readme bits

2022-09-14 08:34 UTC, porstswigger-tim commented
Apologies for the delayed response, I'll add to the documentation and resolve merge conflicts at some point today :)

2022-09-16 10:43 UTC, porstswigger-tim commented
@josvazg - Hey 👋  - all up to date now :) thanks for your patience.

2022-09-19 15:23 UTC, josvazg approved these changes
LGTM

2022-09-19 15:25 UTC, merged